# Generated by Django 6.0.5 on 2026-05-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0004_availabilityslot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.UniqueConstraint(fields=('player', 'week_start_date', 'day_of_week', 'start_time', 'end_time'), name='unique_player_availability_slot'),
        ),
    ]
