# Generated by Django 6.0.5 on 2026-06-03 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0005_availabilityslot_unique_player_availability_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladderstanding',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_week_start_date', models.DateField()),
                ('proposed_day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('proposed_start_time', models.TimeField()),
                ('proposed_end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenger_players', models.ManyToManyField(blank=True, related_name='challenger_challenges', to='ladder.playerprofile')),
                ('challenger_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_challenges', to='ladder.team')),
                ('opponent_players', models.ManyToManyField(blank=True, related_name='opponent_challenges', to='ladder.playerprofile')),
                ('opponent_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_challenges', to='ladder.team')),
            ],
        ),
    ]
