# Generated by Django 6.0.5 on 2026-06-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0007_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResultSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a_sets_won', models.PositiveIntegerField()),
                ('team_b_sets_won', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_submissions', to='ladder.match')),
                ('submitting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'submitting_team'), name='unique_result_submission_per_team_per_match')],
            },
        ),
    ]
