# Generated by Django 6.0.5 on 2026-07-23 19:26

from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


CLUB_TIMEZONE = ZoneInfo("America/New_York")
DAY_OFFSETS = {
    "monday": 0,
    "tuesday": 1,
    "wednesday": 2,
    "thursday": 3,
    "friday": 4,
    "saturday": 5,
    "sunday": 6,
}


def backfill_memberships(apps, schema_editor):
    PlayerProfile = apps.get_model("ladder", "PlayerProfile")
    TeamMembership = apps.get_model("ladder", "TeamMembership")
    for player in PlayerProfile.objects.exclude(team__isnull=True).iterator():
        TeamMembership.objects.get_or_create(
            player_id=player.id,
            team_id=player.team_id,
            status="active",
            defaults={"effective_from": player.created_at},
        )


def reverse_backfill_memberships(apps, schema_editor):
    TeamMembership = apps.get_model("ladder", "TeamMembership")
    TeamMembership.objects.filter(status="active").delete()


def backfill_intervals(apps, schema_editor):
    AvailabilitySlot = apps.get_model("ladder", "AvailabilitySlot")
    for slot in AvailabilitySlot.objects.filter(starts_at__isnull=True, ends_at__isnull=True).iterator():
        slot_date = slot.week_start_date + timedelta(days=DAY_OFFSETS[slot.day_of_week])
        starts_at = datetime.combine(slot_date, slot.start_time, tzinfo=CLUB_TIMEZONE)
        ends_at = datetime.combine(slot_date, slot.end_time, tzinfo=CLUB_TIMEZONE)
        if starts_at < ends_at:
            slot.starts_at = starts_at
            slot.ends_at = ends_at
            slot.status = "active"
            slot.save(update_fields=["starts_at", "ends_at", "status"])

    Match = apps.get_model("ladder", "Match")
    for match in Match.objects.filter(scheduled_starts_at__isnull=True, scheduled_ends_at__isnull=True).iterator():
        match_date = match.scheduled_week_start_date + timedelta(days=DAY_OFFSETS[match.scheduled_day_of_week])
        starts_at = datetime.combine(match_date, match.scheduled_start_time, tzinfo=CLUB_TIMEZONE)
        ends_at = datetime.combine(match_date, match.scheduled_end_time, tzinfo=CLUB_TIMEZONE)
        if starts_at < ends_at:
            match.scheduled_starts_at = starts_at
            match.scheduled_ends_at = ends_at
            match.save(update_fields=["scheduled_starts_at", "scheduled_ends_at"])


def reverse_backfill_intervals(apps, schema_editor):
    AvailabilitySlot = apps.get_model("ladder", "AvailabilitySlot")
    AvailabilitySlot.objects.update(starts_at=None, ends_at=None)
    Match = apps.get_model("ladder", "Match")
    Match.objects.update(scheduled_starts_at=None, scheduled_ends_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0009_adminnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('a', 'Team A'), ('b', 'Team B')], max_length=1)),
                ('lineup_order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchResultSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_order', models.PositiveSmallIntegerField()),
                ('set_type', models.CharField(choices=[('regular', 'Regular set'), ('match_tiebreak', 'Match tie-break')], max_length=30)),
                ('team_a_score', models.PositiveSmallIntegerField()),
                ('team_b_score', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('set_order',),
            },
        ),
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('partially_accepted', 'Partially accepted'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='proposed', max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_delta', models.IntegerField()),
                ('reason', models.CharField(default='match_result', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('a', 'Team A'), ('b', 'Team B')], max_length=1)),
                ('lineup_order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('removal_requested', 'Removal requested')], default='active', max_length=30)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('removal_requested_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('score_conflict', 'Score conflict')], default='score_conflict', max_length=40),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('reserved', 'Reserved'), ('consumed', 'Consumed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='scheduled_ends_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='scheduled_starts_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='matchresultsubmission',
            name='submitting_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_result_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['player', 'status', 'starts_at', 'ends_at'], name='availability_player_window_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='availability_window_idx'),
        ),
        migrations.RunPython(backfill_intervals, reverse_backfill_intervals),
        migrations.AddConstraint(
            model_name='adminnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_resolved', False)), fields=('match', 'notification_type'), name='unique_unresolved_notification_per_match_type'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('player', 'starts_at', 'ends_at'), name='unique_active_player_availability_interval'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('starts_at__lt', models.F('ends_at')), _connector='OR'), name='availability_interval_valid'),
        ),
        migrations.AddField(
            model_name='confirmedmatchresult',
            name='confirmed_from_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_results', to='ladder.matchresultsubmission'),
        ),
        migrations.AddField(
            model_name='confirmedmatchresult',
            name='losing_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_losses', to='ladder.team'),
        ),
        migrations.AddField(
            model_name='confirmedmatchresult',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_result', to='ladder.match'),
        ),
        migrations.AddField(
            model_name='confirmedmatchresult',
            name='winning_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_wins', to='ladder.team'),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ladder.match'),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_participations', to='ladder.playerprofile'),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_participants', to='ladder.team'),
        ),
        migrations.AddField(
            model_name='matchreservation',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_reservations', to='ladder.availabilityslot'),
        ),
        migrations.AddField(
            model_name='matchreservation',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='ladder.match'),
        ),
        migrations.AddField(
            model_name='matchreservation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_reservations', to='ladder.playerprofile'),
        ),
        migrations.AddField(
            model_name='matchresultset',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='ladder.matchresultsubmission'),
        ),
        migrations.AddField(
            model_name='matchsuggestion',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_a_suggestions', to='ladder.team'),
        ),
        migrations.AddField(
            model_name='matchsuggestion',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_b_suggestions', to='ladder.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='source_suggestion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_match', to='ladder.matchsuggestion'),
        ),
        migrations.AddField(
            model_name='pointledger',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point_ledger_entries', to='ladder.match'),
        ),
        migrations.AddField(
            model_name='pointledger',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point_ledger_entries', to='ladder.team'),
        ),
        migrations.AddField(
            model_name='suggestionacceptance',
            name='accepted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestion_acceptances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestionacceptance',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='ladder.matchsuggestion'),
        ),
        migrations.AddField(
            model_name='suggestionacceptance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestion_acceptances', to='ladder.team'),
        ),
        migrations.AddField(
            model_name='suggestionparticipant',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestion_participants', to='ladder.playerprofile'),
        ),
        migrations.AddField(
            model_name='suggestionparticipant',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ladder.matchsuggestion'),
        ),
        migrations.AddField(
            model_name='suggestionparticipant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestion_participants', to='ladder.team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_memberships', to='ladder.playerprofile'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='ladder.team'),
        ),
        migrations.AddConstraint(
            model_name='confirmedmatchresult',
            constraint=models.CheckConstraint(condition=models.Q(('winning_team', models.F('losing_team')), _negated=True), name='confirmed_result_teams_distinct'),
        ),
        migrations.AddIndex(
            model_name='matchparticipant',
            index=models.Index(fields=['match', 'side', 'lineup_order'], name='match_participant_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchparticipant',
            constraint=models.UniqueConstraint(fields=('match', 'player'), name='unique_player_per_match'),
        ),
        migrations.AddConstraint(
            model_name='matchparticipant',
            constraint=models.UniqueConstraint(fields=('match', 'side', 'lineup_order'), name='unique_match_side_order'),
        ),
        migrations.AddIndex(
            model_name='matchreservation',
            index=models.Index(fields=['player', 'status', 'starts_at', 'ends_at'], name='reservation_conflict_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchreservation',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='reservation_interval_valid'),
        ),
        migrations.AddConstraint(
            model_name='matchreservation',
            constraint=models.UniqueConstraint(fields=('match', 'player'), name='unique_reservation_per_match_player'),
        ),
        migrations.AddConstraint(
            model_name='matchresultset',
            constraint=models.UniqueConstraint(fields=('submission', 'set_order'), name='unique_result_set_order'),
        ),
        migrations.AddConstraint(
            model_name='matchresultset',
            constraint=models.CheckConstraint(condition=models.Q(('team_a_score', models.F('team_b_score')), _negated=True), name='result_set_not_tied'),
        ),
        migrations.AddIndex(
            model_name='matchsuggestion',
            index=models.Index(fields=['team_a', 'status', 'expires_at'], name='suggestion_team_a_status_idx'),
        ),
        migrations.AddIndex(
            model_name='matchsuggestion',
            index=models.Index(fields=['team_b', 'status', 'expires_at'], name='suggestion_team_b_status_idx'),
        ),
        migrations.AddIndex(
            model_name='matchsuggestion',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='suggestion_status_window_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchsuggestion',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='suggestion_interval_valid'),
        ),
        migrations.AddConstraint(
            model_name='matchsuggestion',
            constraint=models.CheckConstraint(condition=models.Q(('team_a', models.F('team_b')), _negated=True), name='suggestion_teams_distinct'),
        ),
        migrations.AddIndex(
            model_name='pointledger',
            index=models.Index(fields=['team', 'created_at'], name='point_ledger_team_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointledger',
            constraint=models.UniqueConstraint(fields=('match', 'team', 'reason'), name='unique_point_ledger_entry'),
        ),
        migrations.AddIndex(
            model_name='suggestionacceptance',
            index=models.Index(fields=['suggestion', 'team'], name='suggestion_acceptance_idx'),
        ),
        migrations.AddConstraint(
            model_name='suggestionacceptance',
            constraint=models.UniqueConstraint(fields=('suggestion', 'team'), name='unique_suggestion_acceptance_per_team'),
        ),
        migrations.AddIndex(
            model_name='suggestionparticipant',
            index=models.Index(fields=['suggestion', 'side', 'lineup_order'], name='suggest_part_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='suggestionparticipant',
            constraint=models.UniqueConstraint(fields=('suggestion', 'player'), name='unique_player_per_suggestion'),
        ),
        migrations.AddConstraint(
            model_name='suggestionparticipant',
            constraint=models.UniqueConstraint(fields=('suggestion', 'side', 'lineup_order'), name='unique_suggestion_side_order'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'status'], name='membership_team_status_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['player', 'status'], name='membership_player_status_idx'),
        ),
        migrations.RunPython(backfill_memberships, reverse_backfill_memberships),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('player',), name='unique_active_membership_per_player'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__lt', models.F('effective_to')), _connector='OR'), name='membership_effective_range_valid'),
        ),
    ]
