# Generated by Django 6.0.5 on 2026-07-29 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0010_confirmedmatchresult_matchparticipant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCorrectionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('conflict_resolution', 'Conflict resolution')], default='conflict_resolution', max_length=40)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_correction_audits', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_correction_audits', to='ladder.match')),
                ('new_losing_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_correction_losses', to='ladder.team')),
                ('new_winning_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_correction_wins', to='ladder.team')),
                ('official_submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_score_corrections', to='ladder.matchresultsubmission')),
                ('previous_losing_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_score_correction_losses', to='ladder.team')),
                ('previous_winning_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_score_correction_wins', to='ladder.team')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'created_at'], name='score_audit_match_created_idx')],
            },
        ),
    ]
