# Generated by Django 6.0.7 on 2026-08-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0012_postgresql_overlap_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('join_requested', 'Join requested'), ('removal_requested', 'Removal requested')], default='active', max_length=30),
        ),
    ]
