# Generated by Django 6.0.7 on 2026-08-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ladder", "0013_alter_teammembership_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("join_request_created", "Join request created"),
                            ("join_request_cancelled", "Join request cancelled"),
                            ("join_request_approved", "Join request approved"),
                            ("join_request_rejected", "Join request rejected"),
                            ("match_confirmed", "Match confirmed"),
                            ("match_cancelled", "Match cancelled"),
                            ("score_submitted", "Score submitted"),
                            ("score_conflict_created", "Score conflict created"),
                            ("score_conflict_resolved", "Score conflict resolved"),
                        ],
                        max_length=40,
                    ),
                ),
                ("dedupe_key", models.CharField(max_length=160, unique=True)),
                ("previous_state", models.CharField(blank=True, max_length=40)),
                ("new_state", models.CharField(blank=True, max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_events_as_actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_events",
                        to="ladder.match",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_events",
                        to="ladder.teammembership",
                    ),
                ),
                (
                    "score_correction_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_events",
                        to="ladder.scorecorrectionaudit",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_events",
                        to="ladder.matchresultsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [models.Index(fields=["event_type", "created_at"], name="workflow_type_created_idx")],
            },
        ),
        migrations.CreateModel(
            name="WorkflowEventRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="ladder.workflowevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_event_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user", "created_at"], name="workflow_recipient_created_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("event", "user"), name="unique_workflow_event_recipient")
                ],
            },
        ),
    ]
