# Generated by Django 6.1 on 2026-09-09 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0014_workflowevent_workfloweventrecipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowevent',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_events', to='ladder.matchsuggestion'),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='event_type',
            field=models.CharField(choices=[('join_request_created', 'Join request created'), ('join_request_cancelled', 'Join request cancelled'), ('join_request_approved', 'Join request approved'), ('join_request_rejected', 'Join request rejected'), ('match_request_created', 'Match request created'), ('match_confirmed', 'Match confirmed'), ('match_cancelled', 'Match cancelled'), ('score_submitted', 'Score submitted'), ('score_conflict_created', 'Score conflict created'), ('score_conflict_resolved', 'Score conflict resolved')], max_length=40),
        ),
        migrations.CreateModel(
            name='EmailNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('match_request', 'Match request'), ('score_conflict', 'Score conflict')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=160)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_deliveries', to='ladder.workflowevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='email_delivery_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_email_delivery_event_user')],
            },
        ),
    ]
