# Generated by Django 6.0.8 on 2026-09-17 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ladder", "0019_ratelimitevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchsuggestion",
            name="version",
        ),
        migrations.RemoveField(
            model_name="suggestionacceptance",
            name="accepted_version",
        ),
    ]
