# Generated by Django 6.0.8 on 2026-09-17 02:15

from django.db import migrations


def backfill_legacy_team_memberships(apps, schema_editor):
    PlayerProfile = apps.get_model("ladder", "PlayerProfile")
    TeamMembership = apps.get_model("ladder", "TeamMembership")
    database = schema_editor.connection.alias
    active_player_ids = set(
        TeamMembership.objects.using(database).filter(status="active").values_list("player_id", flat=True)
    )
    rows = [
        TeamMembership(
            player_id=profile.pk,
            team_id=profile.team_id,
            status="active",
            effective_from=profile.created_at,
        )
        for profile in PlayerProfile.objects.using(database).exclude(team_id=None).iterator()
        if profile.pk not in active_player_ids
    ]
    TeamMembership.objects.using(database).bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0020_remove_unused_suggestion_version'),
    ]

    operations = [
        migrations.RunPython(backfill_legacy_team_memberships, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='playerprofile',
            name='team',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
    ]
