# Generated by Django 6.0.8 on 2026-09-22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ladder", "0021_remove_legacy_team_and_challenge"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InviteCode",
        ),
    ]
