"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


DEVELOPMENT_SECRET_KEY = "bc-ladder-development-only-secret-key"

# Development fallback only. Set DJANGO_SECRET_KEY in every deployed environment.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", DEVELOPMENT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", "")


# Application definition

INSTALLED_APPS = [
    'ladder',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get("DATABASE_URL"):
    raise RuntimeError(
        "DATABASE_URL parsing is not configured. Set DJANGO_DB_ENGINE, DJANGO_DB_NAME, "
        "DJANGO_DB_USER, DJANGO_DB_PASSWORD, DJANGO_DB_HOST, and DJANGO_DB_PORT instead."
    )

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DJANGO_DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("DJANGO_DB_NAME", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("DJANGO_DB_USER", ""),
        "PASSWORD": os.environ.get("DJANGO_DB_PASSWORD", ""),
        "HOST": os.environ.get("DJANGO_DB_HOST", ""),
        "PORT": os.environ.get("DJANGO_DB_PORT", ""),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "America/New_York")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

LOGIN_URL = "ladder:login"
LOGIN_REDIRECT_URL = "ladder:dashboard"
LOGOUT_REDIRECT_URL = "ladder:login"

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", False)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", not DEBUG)
SECURE_PROXY_SSL_HEADER_NAME = os.environ.get("DJANGO_SECURE_PROXY_SSL_HEADER_NAME", "")
SECURE_PROXY_SSL_HEADER_VALUE = os.environ.get("DJANGO_SECURE_PROXY_SSL_HEADER_VALUE", "")
SECURE_PROXY_SSL_HEADER = (
    (SECURE_PROXY_SSL_HEADER_NAME, SECURE_PROXY_SSL_HEADER_VALUE)
    if SECURE_PROXY_SSL_HEADER_NAME and SECURE_PROXY_SSL_HEADER_VALUE
    else None
)
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)
SECURE_REFERRER_POLICY = os.environ.get("DJANGO_SECURE_REFERRER_POLICY", "same-origin")


def validate_production_settings():
    errors = production_settings_errors(
        debug=DEBUG,
        secret_key=SECRET_KEY,
        secret_key_was_set=bool(os.environ.get("DJANGO_SECRET_KEY")),
        allowed_hosts=ALLOWED_HOSTS,
        session_cookie_secure=SESSION_COOKIE_SECURE,
        csrf_cookie_secure=CSRF_COOKIE_SECURE,
        secure_ssl_redirect=SECURE_SSL_REDIRECT,
        proxy_ssl_header_name=SECURE_PROXY_SSL_HEADER_NAME,
        proxy_ssl_header_value=SECURE_PROXY_SSL_HEADER_VALUE,
        hsts_seconds=SECURE_HSTS_SECONDS,
        hsts_include_subdomains=SECURE_HSTS_INCLUDE_SUBDOMAINS,
        hsts_preload=SECURE_HSTS_PRELOAD,
    )

    if errors:
        raise ImproperlyConfigured("Unsafe production settings: " + " ".join(errors))


def production_settings_errors(
    *,
    debug,
    secret_key,
    secret_key_was_set,
    allowed_hosts,
    session_cookie_secure,
    csrf_cookie_secure,
    secure_ssl_redirect,
    proxy_ssl_header_name,
    proxy_ssl_header_value,
    hsts_seconds,
    hsts_include_subdomains,
    hsts_preload,
):
    if debug:
        return []

    errors = []
    if not secret_key_was_set or secret_key == DEVELOPMENT_SECRET_KEY or len(secret_key) < 32:
        errors.append("DJANGO_SECRET_KEY must be set to a rotated secret of at least 32 characters.")
    if not allowed_hosts:
        errors.append("DJANGO_ALLOWED_HOSTS must list the deployed hostnames.")
    if "*" in allowed_hosts:
        errors.append("DJANGO_ALLOWED_HOSTS must not contain '*' in production.")
    if any(host in {"localhost", "127.0.0.1", "[::1]"} for host in allowed_hosts):
        errors.append("DJANGO_ALLOWED_HOSTS must not contain local development hosts in production.")
    if not session_cookie_secure:
        errors.append("DJANGO_SESSION_COOKIE_SECURE must be true in production.")
    if not csrf_cookie_secure:
        errors.append("DJANGO_CSRF_COOKIE_SECURE must be true in production.")
    if not secure_ssl_redirect:
        errors.append("DJANGO_SECURE_SSL_REDIRECT must be true in production.")
    if bool(proxy_ssl_header_name) != bool(proxy_ssl_header_value):
        errors.append(
            "Set both DJANGO_SECURE_PROXY_SSL_HEADER_NAME and "
            "DJANGO_SECURE_PROXY_SSL_HEADER_VALUE, or set neither."
        )
    if hsts_preload and not hsts_include_subdomains:
        errors.append("DJANGO_SECURE_HSTS_PRELOAD requires DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=true.")
    if hsts_preload and hsts_seconds < 31536000:
        errors.append("DJANGO_SECURE_HSTS_PRELOAD requires DJANGO_SECURE_HSTS_SECONDS >= 31536000.")
    return errors

validate_production_settings()
